In [1]:
import numpy as np

In [2]:
c = np.arange(24).reshape(4,2,3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [3]:
print(c.ndim)

3


In [5]:
##Indexing a 3D array:
syntax:

array_name[(array_index_no, row_index, column_index)]

In [6]:
print(c[(3,1,1)])

22


In [7]:
print(c[3,0:,1])

[19 22]


In [8]:
print(c[1,0:,:2])

[[ 6  7]
 [ 9 10]]
