In [1]:
import numpy as np

In [3]:
##Boolean Array Indexing:

In Boolean array indexing, the resultant array object is due to the 
result of a boolean expression 

In [4]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
#in this example items greater than 5 are selected as a result of boolean indexing.

print(x[x>5])

[ 6  7  8  9 10 11 12]


In [8]:
#selecting items less than 10:
print(x[x<10])

[1 2 3 4 5 6 7 8 9]


In [11]:
#selecting all items except 10 to 12:
print(x[x!=[10,11,12]])

[1 2 3 4 5 6 7 8 9]


In [12]:
#selecting even items: 
print(x[x%2==0])

[ 2  4  6  8 10 12]


In [13]:
#selecting odd items:
print(x[x%2!=0])

[ 1  3  5  7  9 11]
