In [16]:
import numpy as np

In [17]:
## Integer Array Indexing:

Integer array indexing helps us select an item in an array based on its
Ndarray index.

In [18]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
b = a[[0,1,2], [0,1,0]]
print(b)

[1 4 5]


In [20]:
The above index selection includes items at positions (0,0), (1,1) and (2,0)

In [21]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])

y = x[rows,cols]
print(y)

[[ 1  3]
 [10 12]]


In [24]:
z = x[1:4,1:3]
print(z)

[[ 5  6]
 [ 8  9]
 [11 12]]


In [25]:
y = x[1:4,[1,2]]
print(y)

[[ 5  6]
 [ 8  9]
 [11 12]]
