In [1]:
import numpy as np

In [2]:
# Creating 1d array
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(x.ndim)

1


In [5]:
# Creating 2d array:

y = np.arange(12).reshape(3,4)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
print(y.ndim)

2


In [7]:
# Creating 3d array:

z = np.arange(24).reshape(4,3,2)
print(z)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [8]:
print(z.ndim)

3


In [9]:
print(type(z))

<class 'numpy.ndarray'>
