In [ ]:
Numpy arrays can be created in different ways.
There are several array creation routines in Numpy which are used to create ndarray objects.
Following are the various array creation routines available:

numpy.empty() ----> creates an uninitialized array of specified shape and datatype.
numpy.zeros() ----> creates an array filled with zeros.
numpy.ones()  ----> creates an array filled with ones.
numpy.eye()   ----> creates a 2d array with ones on the diagonal and zeros elsewhere.
numpy.identity() ----> returns the identity array [1's on main diagonal]
numpy.arange() -----> creates an array with a specified range.
numpy.mat() ------> interpret the input as a matrix
numpy.full() ------> returns a new array filled with a fill value 
numpy.asarray() ----> converts a sequence type into a numpy array                                                   

In [30]:
# first import the numpy library:
import numpy as np

In [ ]:
#numpy.empty syntax:
numpy.empty(shape_of_array, dtype) 

In [34]:
a = np.empty([2,2], dtype=int)
print(a)

[[1 2]
 [3 4]]


In [29]:
#numpy.zeros syntax:
numpy.zeros(shape, dtype)

NameError: name 'numpy' is not defined

In [35]:
x = np.zeros([2,2], dtype=int)
print(x)

[[0 0]
 [0 0]]


In [ ]:
#numpy.ones syntax:
numpy.ones(shape,dtype)

In [5]:
x = np.ones([2,2])
print(x)

[[1. 1.]
 [1. 1.]]


In [ ]:
numpy.eye(N,M,k=0,dtype)
where 
N --> no. of rows
M --> no. of columns
k --> index of the diagonal

In [44]:
x = np.eye(3,k=0, dtype=int)
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [15]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#numpy.identity(n,dtype)

x = np.identity(4, dtype=int)
print(x)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [20]:
#numpy.arange(value,<start><stop><step>):

x = np.arange(10)
print(x)

y = np.arange(0,10)
print(y)

z = np.arange(0,10,2)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [22]:
#numpy.mat(data, dtype)

x = np.mat([(1,2,3),(4,5,6),(7,8,9)], dtype=int)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
x = np.array([[1,2],[3,4],[5,6]])

y = np.asmatrix(x)
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [48]:
print(type(x))

<class 'numpy.ndarray'>


In [45]:
#np.full(shape, fill_value)

x = np.full(shape=(2,3), fill_value=7)
print(x)

[[7 7 7]
 [7 7 7]]


In [ ]:
#numpy.asarray(data, dtype)
where
a ---> i/p data [lists, tuples, ndarrays] that can be converted to an array. 

In [26]:
x = np.asarray([[1,2],[3,4]], dtype=int)
print(x)

[[1 2]
 [3 4]]


In [27]:
x = np.asarray(np.array([(1,2,3),(4,5,6)]), dtype=int)
print(x)
            

[[1 2 3]
 [4 5 6]]


In [ ]:
x = np.asarray([(1,2,3),(4,5,6)])

In [46]:
x = np.asarray([1,2,3,4,5], dtype=int)
print(x)

[1 2 3 4 5]


In [47]:
x = np.asarray([(1,2),(3,4)])
print(x)

[[1 2]
 [3 4]]


In [49]:
print(type(x))

<class 'numpy.ndarray'>
