In [1]:
# importing the numpy library:
import numpy as np

In [27]:
# creating a single dimensional (rank 1) array:
x = np.array([1,2,3,4,5])

#displaying the array:
print(x)

[1 2 3 4 5]


In [28]:
# checking the data type of the array:
print(x.dtype)

int64


In [29]:
print(type(x))

<class 'numpy.ndarray'>


In [30]:
# checking the shape of array object:
print(x.shape)

(5,)


In [31]:
# size:
print(x.size)

5


In [41]:
# chceking the number of dimensions:
print(x.ndim)

1


In [38]:
# Accessing array elements (Indexing):
print(x[0])
print(x[-1])
print(x[0], x[2], x[4])
print(x[1], x[3])

1
5
1 3 5
2 4


In [6]:
# Creating multi dimensional arrays

y = np.array([(1,2,3), (4,5,6)])
print(y)


[[1 2 3]
 [4 5 6]]


In [44]:
z = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(z)
print(z.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [7]:
print(y.dtype)

int64


In [42]:
#size
print(y.size)

#shape
print(y.shape)

#no. of dimensions
print(y.ndim)

6
(2, 3)
2


In [9]:
# Creating a array with different data types

# creating an array of int datatype:
a = np.array([1,2,3], dtype = int)
print(a)



[1 2 3]


In [10]:
# creating an array of float datatype:
b = np.array([1,2,3], dtype = float)
print(b)

[1. 2. 3.]


In [11]:
# creating an array of complex datatype:
c = np.array([1,2,3], dtype = complex)
print(c)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
Even you have the functionality of creating a structured data type and
apply it to a ndarray object. This type of data type is also called 
Structured data type.

Let's see a use case below:

In [21]:
# Creating a Structured data type:
dt_1 = np.dtype([('age', np.int8)])
print(dt_1)

[('age', 'i1')]


In [22]:
# applying the above data type to an ndarray object:
a = np.array([(25,), (28,), (30,)], dtype = dt_1)
print(a)

[(25,) (28,) (30,)]


In [23]:
# accessing the values present in age column:
print(a['age'])

[25 28 30]


In [46]:
# creating an array with user defined data type:

#first create a user defined data type:
emp = np.dtype([('eno','i4'), ('ename', 'S20'), ('age','i4'), ('loc', 'S20')])

#applying the above data type to an array object:
Employees = np.array([(101, 'Snigdha', 25, 'Hyderabad'),
                     (102, 'Neha', 25, 'Hyderabad'),
                     (103, 'Kousik', 26, 'Bangalore'),
                     (104, 'Aravind', 27, 'Hyderabad'),
                     (105, 'Kiran', 30, 'Chennai'),
                     (106, 'Abdul', 30, 'Mumbai')])

# displaying the array:
print(Employees)

[['101' 'Snigdha' '25' 'Hyderabad']
 ['102' 'Neha' '25' 'Hyderabad']
 ['103' 'Kousik' '26' 'Bangalore']
 ['104' 'Aravind' '27' 'Hyderabad']
 ['105' 'Kiran' '30' 'Chennai']
 ['106' 'Abdul' '30' 'Mumbai']]


In [ ]:
Note: Each built-in data types has a unique single character code:
        b ----> boolean
        i ----> ineger
        f ----> float
        S ----> String
        c ----> complex 
        M ----> datetime 