In [5]:
import numpy as np

#creating an array with sequence of elements:
x = np.array([(1,2,3), (4,5,6), (7,8,9), (10,11,12)])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
## RESHAPING:

#Method 1:

#reshaping an array using shape:
x.shape = [3,4]
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
x.shape = [2,6]
print(x)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
#Method 2:

#reshaping using the reshape function:
y = x.reshape(6,2)
print(y)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [10]:
# Working on Dimensions:

#creating an array using the arange function:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
print(a.ndim)

1


In [11]:
b = a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
print(b.ndim)

2


In [12]:
##reshaping a multi dimension array using the reshape function:

c = b.reshape(2,2,3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [13]:
print(c.ndim)

3
